# Generated by Django 5.2.17 on 2026-09-29 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('chat', '0001_initial'),
        ('llm', '0002_seed_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_label', models.CharField(help_text='Snapshot of the session ID and name.', max_length=150)),
                ('input_tokens', models.PositiveIntegerField()),
                ('output_tokens', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=6, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='billing.billingaccount')),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='llm.llmmodel')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge', to='chat.message')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
