# Generated by Django 5.2.17 on 2026-09-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='name_set_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
