# Generated by Django 5.2.17 on 2026-09-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], max_length=20)),
                ('api_model', models.CharField(help_text='Model ID sent to the proxy.', max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('tier', models.CharField(choices=[('value', 'Value'), ('standard', 'Standard'), ('premium', 'Premium')], default='value', max_length=20)),
                ('input_price_per_mtok', models.DecimalField(decimal_places=4, max_digits=10)),
                ('output_price_per_mtok', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'LLM model',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
    ]
